# 情感分类

In [1]:
import pandas as pd


id2tokens = pd.read_csv('data/id2tokens.csv', names=["id", "tokens"])
id2tokens.head()

   id tokens
0   0      !
1   1     !?
2   2      '
3   3     ''
4   4   '30s

In [2]:
tokens2id = pd.read_csv('data/tokens2id.csv', names=["tokens", "id"])
tokens2id.head()

  tokens  id
0      !   0
1     !?   1
2      '   2
3     ''   3
4   '30s   4

In [3]:
train_data = pd.read_csv('data/train.csv')
train_data.head()

                                           sentences  label
0  ['the', 'rock', 'is', 'destined', 'to', 'be', ...      3
1  ['the', 'gorgeously', 'elaborate', 'continuati...      4
2  ['singer', 'composer', 'bryan', 'adams', 'cont...      3
3  ['you', "'d", 'think', 'by', 'now', 'america',...      2
4  ['yet', 'the', 'act', 'is', 'still', 'charming...      3

In [4]:
len(train_data)

8544

In [5]:
eval_data = pd.read_csv('data/dev.csv')
test_data = pd.read_csv('data/test.csv')
len(eval_data), len(test_data)

(1101, 2210)

In [5]:
id2tokens = dict(zip(id2tokens["id"], id2tokens["tokens"]))
tokens2id = dict(zip(tokens2id["tokens"], tokens2id["id"]))

In [6]:
lens = []
for sentence in train_data["sentences"]:
    lens.append(len(eval(sentence)))

In [7]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Histogram(x=lens, nbinsx=50)])
fig.update_layout(
    title="Sentence Length Distribution",
    xaxis_title="Sentence Length",
    yaxis_title="Count",
    bargap=0.2,
)
fig.show()

In [24]:
import numpy as np
import plotly.graph_objects as go


bs = np.array([64, 128, 256])
hs = np.array([128, 256, 512])
xs, ys = np.meshgrid(bs, hs)
accs = np.array([[45.87, 43.23, 44.32], [45.87, 44.60, 45.32], [46.23, 46.05, 45.14]])
fig = go.Figure(data=[
    go.Surface(x=hs, y=bs, z=accs, colorscale='Viridis', opacity=0.7, colorbar=dict(title='Val Accuracy')),
    go.Scatter3d(x=[128], y=[256], z=[46.23], mode="markers", marker={"size": 4, "color": "red"}, name="Best")
])
fig.update_xaxes(type="log")
fig.update_yaxes(type="log")
fig.update_layout(
    height=800,
    title="Validation Accuracy for Different Hyperparameters",
    scene=dict(
        xaxis_title="Hidden Dim",
        yaxis_title="Batch Size",
        zaxis_title="Val Accuracy"
    ))
fig.show()